const ACCESS_TOKEN_EXPIRE_DATE = process.env.ACCESS_TOKEN_EXPIRE_DATE;
const REFRESH_TOKEN_EXPIRE_DATE = process.env.REFRESH_TOKEN_EXPIRE_DATE;
const ACCESS_TOKEN_PRIVATE_KEY = process.env.ACCESS_TOKEN_PRIVATE_KEY.replace(/\\n/g, '\n');
const ACCESS_TOKEN_PUBLIC_KEY = process.env.ACCESS_TOKEN_PUBLIC_KEY.replace(/\\n/g, '\n');
const REFRESH_TOKEN_PRIVATE_KEY = process.env.REFRESH_TOKEN_PRIVATE_KEY.replace(/\\n/g, '\n');
const REFRESH_TOKEN_PUBLIC_KEY = process.env.REFRESH_TOKEN_PUBLIC_KEY.replace(/\\n/g, '\n');

module.exports ={
    ACCESS_TOKEN_EXPIRE_DATE,
    REFRESH_TOKEN_EXPIRE_DATE,
    ACCESS_TOKEN_PRIVATE_KEY,
    ACCESS_TOKEN_PUBLIC_KEY,
    REFRESH_TOKEN_PRIVATE_KEY,
    REFRESH_TOKEN_PUBLIC_KEY
}